[global]
force_update = yes
use_requirements = no

[uninstall]
python_package = dataclasses

[symlinks]
source_dir = /opt/odoo/odoo-18.0
target_dir = /var/lib/odoo/.local/share/Odoo/addons/18.0

[github]
username = [username]
email = [email]
password = [password]

[addons]
use_oca = no
use_ee = false

[owner]
uid = 100
gid = 101
