[options]
addons_path = /mnt/extra-addons
; data_dir = /var/lib/odoo
db_host = odoo-18-pg-rw
db_port = 5432
db_user = odoo
db_password = odoo16
log_level = info
admin_passwd = SuperPassword
proxy_mode = True
