apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: odoo-18-db
  namespace: odoo-18
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: role
                operator: In
                values:
                  - database
